//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieShowTime
    {
        public int Id { get; set; }
        public Nullable<int> MovieId { get; set; }
        public string StartTime { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
    
        public virtual movie movie { get; set; }
    }
}
